version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - app_network
    ports:
      - "9000:80"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php_db
    environment:
      MYSQL_DATABASE: php_app
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: php_user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    ports:
      - "3309:3306"

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
